---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for existing install
  become: '{{ secretless_broker_privilege_escalate }}'
  stat:
    path: '{{ secretless_broker_install_dir }}'
  changed_when: False
  register: secretless_broker_binary
- when: not secretless_broker_binary.stat.exists
  block:
    - name: download
      become: '{{ secretless_broker_privilege_escalate }}'
      become_user: root
      get_url:
        url: '{{ secretless_broker_url }}'
        dest: /tmp/{{ secretless_broker_archive }}
        checksum: '{{ secretless_broker_checksum }}'
        mode: 0644
    - name: unarchive
      become: '{{ secretless_broker_privilege_escalate }}'
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ secretless_broker_archive }}
        dest: '{{ secretless_broker_parent_install_dir }}'
        creates: '{{ secretless_broker_install_dir }}'
  always:
    - name: cleanup
      become: '{{ secretless_broker_privilege_escalate }}'
      become_user: root
      file:
        path: /tmp/{{ secretless_broker_archive }}
        state: absent
- name: link
  become: '{{ secretless_broker_privilege_escalate }}'
  become_user: root
  with_items:
    - summon2
    - secretless-broker
  file:
    src: '{{ secretless_broker_install_dir }}/{{ item }}'
    dest: '{{ secretless_broker_parent_install_dir }}/bin/{{ item }}'
    state: link
